### ISSUE TITLE
Math my_dpow function always returns 0

### ISSUE THREAD

**Issue by ymougenel** [alexishachemi/my_libC#1]
Hello,
While using using your library for my huge international project, I encountered an issue with the my_dpow function: it always returns 0    (╯°□°)╯︵ ┻━┻

**Related code:** 
https://github.com/alexishachemi/my_libC/blob/f449c928d34805e8f8357d5f4dccd09b04e0e9bf/src/math/math_compute.c#L28

_Note:_ It **might** be related to the variable instantiation ¯\ _(ツ)_/¯

PS: I hope your doing well 😀

**Comment by alexishachemi** [comment]
Hi,
First of all I'd like to apologize for the time it took for me to notice this issue 😅. I'm not sure why I wasn't notified but better late than never right ??

After a thorough investigation of the source code, I have concluded that the issue you've pinpointed is most likely an unfortunate byproduct of variable instantiation as you've already hypothesised.

I'm opening a new branch ASAP to work on the issue.

PS: I am doing fine thank you, I hope everything is alright for you too 😄
